"""Generate the firmware's feature tables and self-test vectors from TensorFlow itself.

Writes (into firmware/hello_tors_kws/main/):
  kws_feature_tables.h  - Hann window, sparse mel filterbank, DCT matrix, taken straight
                          from tf.signal so the C front end matches training exactly.
  kws_test_vectors.h    - two 1 s int16 clips + the int8 features and model output the
                          Python reference produces for them. The firmware runs these at
                          boot as a self-test.
Also checks that hello_tors_model_data.h is byte-identical to the .tflite.

  python tools/gen_firmware_tables.py [--dataset ..\\hello_tors_dataset.zip]

The self-test clips are saved to test_audio/selftest_{pos,neg}.wav; once they exist the
dataset zip is no longer needed to re-run this script.
"""
import argparse, csv, io, os, re, sys, zipfile

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import numpy as np
import soundfile as sf
import tensorflow as tf

from scan_audio import C, SR, WIN, Model, features_batch

MAIN = os.path.join(ROOT, "firmware", "hello_tors_kws", "main")
MODEL = os.path.join(ROOT, "export", "hello_tors_kws_int8.tflite")
POS_WAV = os.path.join(ROOT, "test_audio", "selftest_pos.wav")
NEG_WAV = os.path.join(ROOT, "test_audio", "selftest_neg.wav")


def fmt_floats(vals, per_line=6):
    s = [f"{float(np.float32(v)):.9g}f" for v in vals]
    s = [v if ("." in v or "e" in v) else v.replace("f", ".0f") for v in s]
    return ",\n".join("  " + ", ".join(s[i:i + per_line]) for i in range(0, len(s), per_line))


def fmt_ints(vals, per_line=16):
    s = [str(int(v)) for v in vals]
    return ",\n".join("  " + ", ".join(s[i:i + per_line]) for i in range(0, len(s), per_line))


def feature_tables():
    n_bins = C["fft_length"] // 2 + 1
    hann = tf.signal.hann_window(C["frame_length"], periodic=True).numpy()
    mel = tf.signal.linear_to_mel_weight_matrix(
        C["num_mfcc"], n_bins, SR, C["mel_lower_hz"], C["mel_upper_hz"]).numpy()  # [257, 40]
    # DCT basis exactly as mfccs_from_log_mel_spectrograms applies it: mfcc = D @ log_mel.
    dct = tf.signal.mfccs_from_log_mel_spectrograms(
        tf.eye(C["num_mfcc"], dtype=tf.float32)).numpy().T  # [k][n]

    starts, lens, weights = [], [], []
    for m in range(mel.shape[1]):
        nz = np.nonzero(mel[:, m])[0]
        assert len(nz) and np.all(np.diff(nz) == 1), f"mel band {m} is not contiguous"
        starts.append(nz[0]); lens.append(len(nz)); weights.extend(mel[nz, m])

    out = f"""// Auto-generated by tools/gen_firmware_tables.py from tf.signal - do not edit.
// Feature config: {os.path.relpath(os.path.join(ROOT, 'export', 'feature_config.json'), ROOT)}
#pragma once

#define KWS_TBL_SAMPLE_RATE  {SR}
#define KWS_TBL_FRAME_LEN    {C['frame_length']}
#define KWS_TBL_FRAME_STEP   {C['frame_step']}
#define KWS_TBL_FFT_LEN      {C['fft_length']}
#define KWS_TBL_NUM_MEL      {C['num_mfcc']}
#define KWS_TBL_NUM_MFCC     {C['num_mfcc']}
#define KWS_TBL_NUM_FRAMES   {C['num_frames']}
#define KWS_TBL_LOG_EPSILON  {C['log_epsilon']:.9g}f
#define KWS_TBL_MEL_WEIGHTS  {len(weights)}

// tf.signal.hann_window({C['frame_length']}, periodic=True)
static const float kws_hann[{C['frame_length']}] = {{
{fmt_floats(hann)}
}};

// tf.signal.linear_to_mel_weight_matrix({C['num_mfcc']}, {n_bins}, {SR}, {C['mel_lower_hz']}, {C['mel_upper_hz']}),
// stored sparse: band m uses FFT bins [kws_mel_start[m], kws_mel_start[m] + kws_mel_len[m]).
static const unsigned short kws_mel_start[{C['num_mfcc']}] = {{
{fmt_ints(starts)}
}};
static const unsigned short kws_mel_len[{C['num_mfcc']}] = {{
{fmt_ints(lens)}
}};
static const float kws_mel_weights[{len(weights)}] = {{
{fmt_floats(weights)}
}};

// mfccs_from_log_mel_spectrograms as a matrix: mfcc[k] = sum_n kws_dct[k][n] * log_mel[n]
static const float kws_dct[{C['num_mfcc']}][{C['num_mfcc']}] = {{
""" + ",\n".join("  {\n" + fmt_floats(row) + "\n  }" for row in dct) + "\n};\n"
    with open(os.path.join(MAIN, "kws_feature_tables.h"), "w", newline="\n") as f:
        f.write(out)
    print(f"kws_feature_tables.h: {len(weights)} mel weights, DCT {dct.shape}")


def pick_clips(dataset, model):
    """Choose a clear keyword clip and a near-miss negative from the dataset."""
    z = zipfile.ZipFile(dataset)
    rows = list(csv.DictReader(io.TextIOWrapper(z.open("dataset/manifest.csv"))))
    names = set(z.namelist())

    def load(r):
        p = f"dataset/{'positive' if r['label'] == '1' else 'negative'}/{r['clip']}"
        if p not in names:
            return None
        y = sf.read(io.BytesIO(z.read(p)), dtype="int16")[0]
        return y if len(y) >= WIN else None

    def score(y):
        return float(model(features_batch((y[:WIN] / 32768.0).astype(np.float32)[None])[0])[1])

    pos = neg = None
    for r in rows:
        if r["variant"] != "raw":
            continue
        y = load(r)
        if y is None:
            continue
        if pos is None and r["label"] == "1" and score(y) > 0.9:
            pos = (r["clip"], y)
        if neg is None and r["label"] == "0" and r["kind"] == "nearmiss" and 0.1 < score(y) < 0.5:
            neg = (r["clip"], y)
        if pos and neg:
            break
    assert pos and neg, "could not find suitable self-test clips"
    return pos, neg


def test_vectors(model):
    vecs = []
    for name, path in (("pos", POS_WAV), ("neg", NEG_WAV)):
        pcm = sf.read(path, dtype="int16")[0][:WIN]
        # Same conversion soundfile uses for float reads: int16 / 32768.
        feats = features_batch((pcm / 32768.0).astype(np.float32)[None])[0]
        s, z = model.i["quantization"]
        q = np.clip(np.round(feats / s + z), -128, 127).astype(np.int8)
        model.it.set_tensor(model.i["index"], q[None]); model.it.invoke()
        raw = model.it.get_tensor(model.o["index"])[0]
        os_, oz = model.o["quantization"]
        print(f"self-test {name}: {os.path.basename(path)}  P(keyword) {(raw[1] - oz) * os_:.3f}  raw {raw.tolist()}")
        vecs.append((name, os.path.basename(path), pcm, q, raw))

    out = ["// Auto-generated by tools/gen_firmware_tables.py - do not edit.",
           "// Boot self-test: the firmware recomputes features + inference for these clips",
           "// and compares with what the Python/TensorFlow reference produced.",
           "#pragma once", "#include <stdint.h>", "",
           f"#define KWS_TEST_NUM_SAMPLES {WIN}", ""]
    for name, fname, pcm, q, raw in vecs:
        out += [f"// {fname}",
                f"static const int16_t kws_test_{name}_pcm[{WIN}] = {{", fmt_ints(pcm, 20), "};",
                f"static const int8_t kws_test_{name}_features[{q.size}] = {{", fmt_ints(q.ravel(), 20), "};",
                f"static const int8_t kws_test_{name}_output[2] = {{ {raw[0]}, {raw[1]} }};", ""]
    with open(os.path.join(MAIN, "kws_test_vectors.h"), "w", newline="\n") as f:
        f.write("\n".join(out))


def check_model_header():
    h = open(os.path.join(MAIN, "hello_tors_model_data.h")).read()
    body = h[h.index("g_hello_tors_model_data[]"):h.index("};")]
    data = bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", body))
    assert data == open(MODEL, "rb").read(), "hello_tors_model_data.h does not match the .tflite!"
    print(f"hello_tors_model_data.h matches {os.path.basename(MODEL)} ({len(data)} bytes)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", default=os.path.join(os.path.dirname(ROOT), "hello_tors_dataset.zip"))
    a = ap.parse_args()
    model = Model(MODEL)
    if not (os.path.exists(POS_WAV) and os.path.exists(NEG_WAV)):
        (pn, py), (nn, ny) = pick_clips(a.dataset, model)
        sf.write(POS_WAV, py, SR, subtype="PCM_16")
        sf.write(NEG_WAV, ny, SR, subtype="PCM_16")
        print(f"picked self-test clips: {pn} (keyword), {nn} (near-miss)")
    feature_tables()
    test_vectors(model)
    check_model_header()


if __name__ == "__main__":
    main()
